### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Zakarialabib** [HashashinMaster/fitness-helper#1]
Salamo alaykom, the project looks promising, some suggestions & improvements, to make code readable,
Model naming : Capitalized names makes better dev experience, & will not be confused with variables and properties. 
Controller structu, : looks awful, consider ordering. 
Code formatting : try using laravel pint package

**Comment by Khidir-Karawita** [comment]
Wa alaykom assalam Zakaria, thank you for taking the time to review my code and providing suggestions for improvement. I appreciate your feedback and will take it into consideration as I continue to work on my future projects.
